# -*- coding: utf-8 -*-
"""
Created on Thu Sep 6 14:31:56 2024

@author: raafay
"""
#Author: Mohammad Raafay Shehzad
#Assigntment Name: Homework 1 (NutriBites Market Sales)
#Due Date: September 11, 2024
#Program Description: This program identifies which NutriBite snacks have the highest profit 
#margin and are most popular. It asks the user to input information about the product and 
#then calculates and displays the total revenue, total cost, quantity sold, and total profit for the product.

#%%
#This cell asks the user to input information about the product
product_name = input("What is the name of the product? ")
product_price = float(input("What is the price of this product in dollars? Enter only numbers: "))
product_cost = float(input("How much does this product cost you in dollars? Enter only numbers: "))
quantity_sold = int(input("How much of this product did you sell? Enter only numbers: "))
#%%
#The first line provides a blank space betwwen the user responses and the summary information
#The second  line prints the name of the product the user entered
#The rest of the three lines calculate the total revenue, cost, and profit based on the user input
print("")
print("Name of the product:", product_name)
total_revenue = product_price*quantity_sold
total_cost = product_cost*quantity_sold
total_profit = total_revenue-total_cost
#%%
#This cell displays the total revenue generated by the product
print("Total revenue generated by", product_name, end = "")
print(":", end =" ")
print("$", end = "")
print(format(total_revenue, ".2f"))
#%%
#This cell displays the total cost of the product
print("Total cost of", product_name, end = "")
print(": ", end="")
print("$", end ="")
print(format(total_cost,".2f"))
#%%
#This cell/line displays the quantity of the product sold
print("Quantity of", product_name, "sold:", quantity_sold)
#%% 
#This cell displays the total profit generated by the product
print("Total profit in dollars generated by", end="")
print(":", end=" ")
print("$", end ="")
print(format(total_profit, ".2f"))
#%% 
#This cell displays the profit percentage of the product
profit_percentage = total_profit/total_revenue * 100
print("Percent profit generated by", product_name, end="")
print(":", end=" ")
print(format(profit_percentage,".0f"), end="")
print("%")